/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { GreeterContract } from "./Greeter";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Greeter"): GreeterContract;
    }
  }
}

export { GreeterContract, GreeterInstance } from "./Greeter";
