/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC721Contract } from "./ERC721";
import { ERC721URIStorageContract } from "./ERC721URIStorage";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { ERC165Contract } from "./ERC165";
import { IERC165Contract } from "./IERC165";
import { AuctionContract } from "./Auction";
import { YourCollectibleContract } from "./YourCollectible";
import { YourContractContract } from "./YourContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "Auction"): AuctionContract;
      require(name: "YourCollectible"): YourCollectibleContract;
      require(name: "YourContract"): YourContractContract;
    }
  }
}

export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { AuctionContract, AuctionInstance } from "./Auction";
export {
  YourCollectibleContract,
  YourCollectibleInstance,
} from "./YourCollectible";
export { YourContractContract, YourContractInstance } from "./YourContract";
