/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface YourContractContract
  extends Truffle.Contract<YourContractInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<YourContractInstance>;
}

export interface SetPurpose {
  name: "SetPurpose";
  args: {
    sender: string;
    purpose: string;
    0: string;
    1: string;
  };
}

type AllEvents = SetPurpose;

export interface YourContractInstance extends Truffle.ContractInstance {
  purpose(txDetails?: Truffle.TransactionDetails): Promise<string>;

  setPurpose: {
    (newPurpose: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      newPurpose: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newPurpose: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newPurpose: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    purpose(txDetails?: Truffle.TransactionDetails): Promise<string>;

    setPurpose: {
      (newPurpose: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        newPurpose: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newPurpose: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newPurpose: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
